name: Flutter CI


on:
push:
branches: [ main ]
pull_request:
branches: [ main ]


jobs:
analyze_format:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: subosito/flutter-action@v2
with:
channel: stable
- run: flutter pub get
- run: flutter format --set-exit-if-changed .
- run: flutter analyze