// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUx5ZpQ3bJIJgt2T2ElMwwfO4omUTkMgc',
    appId: '1:601952715042:web:f1f5aa16390fef73e5257b',
    messagingSenderId: '601952715042',
    projectId: 'buybarter',
    authDomain: 'buybarter.firebaseapp.com',
    storageBucket: 'buybarter.firebasestorage.app',
    measurementId: 'G-B57WVL8LQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Xhz8vw6DlXcst-Dhx-yMcDLlylLOl_o',
    appId: '1:601952715042:android:c3f70284a7d8ebcee5257b',
    messagingSenderId: '601952715042',
    projectId: 'buybarter',
    storageBucket: 'buybarter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJch6MpbVN_wqg8CNQ6rUuJm88exDpFKE',
    appId: '1:601952715042:ios:579e8f3fda36c54ae5257b',
    messagingSenderId: '601952715042',
    projectId: 'buybarter',
    storageBucket: 'buybarter.firebasestorage.app',
    iosBundleId: 'com.example.buyrbarter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJch6MpbVN_wqg8CNQ6rUuJm88exDpFKE',
    appId: '1:601952715042:ios:579e8f3fda36c54ae5257b',
    messagingSenderId: '601952715042',
    projectId: 'buybarter',
    storageBucket: 'buybarter.firebasestorage.app',
    iosBundleId: 'com.example.buyrbarter',
  );
}
