import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app.dart'; // <-- your new file

Future<void> main() async {
  // Make sure Flutter can do async work before runApp
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase for web/android/ios using generated config
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Make Riverpod available to the whole widget tree
  runApp(
    const ProviderScope(
      child: MyApp(),
    ),
  );
}
