name: Android Debug APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get

      # Restore YOUR keystore so SHA-1 always matches Firebase
      - name: Restore debug keystore
        run: |
          mkdir -p ~/.android
          echo "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" | base64 --decode > ~/.android/debug.keystore

      - run: |
          if [ ! -d "android" ]; then
            flutter create --platforms=android .
          fi
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
